[context.run]
default = "dx"

[context.run.configs.default]
type = "cargo"
command = "cargo"
sub_command = "run"
sub_action = ""
params = ""
features = []
allow_multiple_instances = false
working_directory = ""
allowed_subcommands = []

[context.run.configs.default.env]

[context.run.configs.dx]
type = "command"
command = "dx"
sub_command = "build"
sub_action = ""
params = ""
features = []
allow_multiple_instances = false
working_directory = ""
allowed_subcommands = [
    "build",
    "bundle",
    "check",
    "clean",
    "config",
    "fmt",
    "init",
    "new",
    "serve",
    "translate",
]

[context.run.configs.dx.env]
WARNINGS = "TRUE"

[context.test]
default = "default"

[context.test.configs.default]
type = "cargo"
command = "cargo"
sub_command = "test"
sub_action = ""
params = ""
features = []
allow_multiple_instances = false
working_directory = ""
allowed_subcommands = []

[context.test.configs.default.env]

[context.build]
default = "default"

[context.build.configs.default]
type = "cargo"
command = "cargo"
sub_command = "build"
sub_action = ""
params = ""
features = []
allow_multiple_instances = false
working_directory = ""
allowed_subcommands = []

[context.build.configs.default.env]

[context.bench]
default = "default"

[context.bench.configs.default]
type = "cargo"
command = "cargo"
sub_command = "bench"
sub_action = ""
params = ""
features = []
allow_multiple_instances = false
working_directory = ""
allowed_subcommands = []

[context.bench.configs.default.env]
