[commands.run]
default = "default"

[commands.run.configs.default]
type = "cargo"
command = "run --package ${packageName} --bin ${binaryName}"
params = ""
allow_multiple_instances = false
working_directory = "${workspaceFolder}"
pre_command = []

[commands.run.configs.default.env]

[commands.run.configs.leptos]
type = "cargo"
command = "leptos"
params = "watch"
allow_multiple_instances = false
working_directory = "${workspaceFolder}"
pre_command = ["default"]

[commands.run.configs.leptos.env]
APP_NAME = "Cargo Runner"
MY_CUSTOM_VAR_1 = "TRUE"
COPY_TRAIT = "FALSE"

[commands.test]
default = "default"

[commands.test.configs.default]
type = "cargo"
command = "test"
params = ""
allow_multiple_instances = false
working_directory = "${workspaceFolder}"
pre_command = []

[commands.test.configs.default.env]

[commands.build]
default = "default"

[commands.build.configs.default]
type = "cargo"
command = "build"
params = ""
allow_multiple_instances = false
working_directory = "${workspaceFolder}"
pre_command = []

[commands.build.configs.default.env]

[commands.bench]
default = "default"

[commands.bench.configs.default]
type = "cargo"
command = "bench"
params = ""
allow_multiple_instances = false
working_directory = "${workspaceFolder}"
pre_command = []

[commands.bench.configs.default.env]
