[commands.run]
default = "default"

[commands.run.configs.default]
type = "cargo"
command = "run --package ${packageName} --bin ${binaryName}"
params = ""
env = {}
allow_multiple_instances = false
working_directory = "${workspaceFolder}"
pre_command = ""


[commands.test]
default = "default"

[commands.test.configs.default]
type = "cargo"
command = "test"
params = ""
env = {}
allow_multiple_instances = false
working_directory = "${workspaceFolder}"
pre_command = ""


[commands.build]
default = "default"

[commands.build.configs.default]
type = "cargo"
command = "build"
params = ""
env = {}
allow_multiple_instances = false
working_directory = "${workspaceFolder}"
pre_command = ""


[commands.bench]
default = "default"

[commands.bench.configs.default]
type = "cargo"
command = "bench"
params = ""
env = {}
allow_multiple_instances = false
working_directory = "${workspaceFolder}"
pre_command = ""
